### ISSUE TITLE
Godot 4.0 etc

### ISSUE THREAD

**Issue by lightyears1998** [2439905184/TerasologyLauncher-Nim#19]
从 https://github.com/lightyears1998/a-gzhu-coder/issues/12 那边过来的。

今天我尝试把 TerasologyLauncher-Nim 的 Godot Launcher 魔改成用 GD 4.0 版本的，然后用 Godot 4 的 Custom Engine Build Profile 功能自己编译了一下 Godot 4.0 的导出模板，发现软件的体积确实没有减少多少。默认的导出模板大小是 65 MB，自行编译的大小是 58 MB。不过 Godot 4 TextServer 重构带来的好处就是可以读取系统的字体了，这样发行的时候就不用自带字体了，可以减少 8 MB左右的体积。

---

PS. 这是 4.0 的默认 UI 外观。

![image](https://user-images.githubusercontent.com/22541353/190550773-d0723be7-3c3b-47bd-8598-4e5e8be8c3aa.png)

**Comment by 2439905184** [comment]
以后4.0可能会考虑，我在等稳定版

**Comment by lightyears1998** [comment]
4.0 现在更新到 beta 1 啦。

用了一下，感觉这个版本带上 GDExtension 进行 Android export 有挺大的问题，感觉是 GDExtension 那边没有适配好。另外神奇的是，LineEdit 的 Wrap Mode 在 Editor 里面跟导出后的表现不一致，导出后似乎会把中文的整个句子识别成类似英语单词的东西，这导致中文排版出现了挺大问题。🤣可能 4.0 正式版还要挺长时间才能发布。

**Comment by lightyears1998** [comment]
> 以后4.0可能会考虑，我在等稳定版

@2439905184 Godot 4.0 正式版发布啦~ 🎈🎈🎈
